name: check_in_presentation
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6
  syncfusion_flutter_calendar: ^20.2.36
  syncfusion_flutter_datepicker: ^20.2.36
  dropdown_button2: ^1.7.0
  flutter_switch: ^0.3.2
  avatar_stack: ^1.1.2
  material_floating_search_bar: ^0.3.4
  provider: ^6.0.1
  implicitly_animated_reorderable_list: ^0.4.0
  phone_form_field:
    git:
      url: https://github.com/stefanmiller1/phone_form_field.git
  dotted_border: ^2.0.0+2
  patterns_canvas: ^0.4.0
  check_in_credentials:
    path: /Users/stefanmiller/AndroidStudioProjects/check_in_credentials
  check_in_facade:
    path: /Users/stefanmiller/AndroidStudioProjects/check_in_facade
  check_in_domain:
    path: /Users/stefanmiller/AndroidStudioProjects/check_in_domain
  check_in_application:
    path: /Users/stefanmiller/AndroidStudioProjects/check_in_application

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 generate: true

  # To add assets to your package, add an assets section, like this:


  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
